### PR TITLE
Removed .py file except main.py issue #8

### LINKED ISSUE #8: Remove all .py files expect main.py
all .py files are rendered useless as the code has already been moved to main.py

### PR DESCRIPTION
**Pull request by jhonsnow456**

### CODE REVIEW

**Comment by Blackcipher101** [comment]
Don't the .gitignore file

**Review by Blackcipher101 — CHANGES_REQUESTED** [review]
Don't add the gitignore file

**Comment by Blackcipher101** [comment]
Also, try to link the issue you trying to do and push from another branch not master.

**Comment by hey-amanthakur** [comment]
Okay I will try to do that

**Comment by Blackcipher101** [comment]
any updates

**Comment by hey-amanthakur** [comment]
Yes, I am looking to it I will surely do it by Sunday facing the network
issue over the weekend

**Review by jhonsnow456 — COMMENTED** [review]
removed gitignore file

**Comment by hey-amanthakur** [comment]
> Also, try to link the issue you trying to do and push from another branch not master.

sir can you tell me whether i have to create a seperate issue over your repo or forked repo I didn't get that

**Comment by Blackcipher101** [comment]
> > Also, try to link the issue you trying to do and push from another branch not master.
> 
> sir can you tell me whether i have to create a seperate issue over your repo or forked repo I didn't get that

Create an issue in my repo

**Comment by Blackcipher101** [comment]
BTW try squashing the commits and next time you send a pr make sure you do it from another branch

**Comment by Blackcipher101** [comment]
> > Also, try to link the issue you trying to do and push from another branch not master.
> 
> sir can you tell me whether i have to create a seperate issue over your repo or forked repo I didn't get that

Don't call me sir makes me feel old 😆 . Call me @Blackcipher101 or Nehal 😄

**Comment by Blackcipher101** [comment]
I am merging it now coz its taking it a lot of time

**Pull request merged**
